substitutions:
  device_name: s0-dongle
  device_description: "S0 module to read S0 interfaces (pulse counters)"
  friendly_name: S0 Dongle
  p_version: "2022.5.1"

esphome:
  name: ${device_name}
  comment: "${device_description}" 
  name_add_mac_suffix: false
  
  project:
    name: smartstuff.s0-dongle
    version: ${p_version}
  
esp8266:
  board: esp12e
  restore_from_flash: true

status_led:
  pin:
    number: 2
    inverted: true

ota:

wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    ap_timeout: 15s
    
dashboard_import:
  package_import_url: github://mhendriks/esphome-p1/s0-dongle.yaml
  
captive_portal:

web_server:
  port: 80
  
# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False

api:
#via Home Assistant Ontwikkelhulpmiddelen > services zoeken op esphome.watermeter_set_water_reading en via deze methode de juiste beginstand invoeren
  services:
    - service: set_s0_value
      variables:
        meter_value: float
      then:
        - globals.set:
            id: last_usage
            value: !lambda 'ESP_LOGI("Service", "Restored value: %f", meter_value); return (meter_value - id(tot_count) );'
        
globals:
  - id: last_usage
    type: float
    restore_value: true  # aanpassen naar no indien de nieuwe waarde onder de oude ligt
    initial_value: '0'   # beginstand  -> aanpassen via Home Assistant services
  - id: tot_count
    type: float
    restore_value: no  # aanpassen naar no indien de nieuwe waarde onder de oude ligt
    initial_value: '0'   # beginstand  -> aanpassen via Home Assistant services

        
button:  
  - platform: restart
    name: "Restart device"  
  
sensor:
  - platform: pulse_counter
    pin: 
      number: 5
      mode:
        input: true
        pullup: true #v3.5 aanzetten
    id: pulse
    state_class: measurement
    update_interval: 5s
#    internal_filter: 100ms
#    accuracy_decimals: 3
    unit_of_measurement: 'kW'
    filters:
      - multiply: 0.06 # (60s/1000 pulses per kWh)
    total:
      name: "S0 Total Energy"
      id: pulse_tot
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
        - lambda: |-
             id(tot_count) = x;
             return id(last_usage) + x;
        - filter_out: NAN

  - platform: uptime
    name: "Uptime"
    
text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP-adres
      icon: mdi:ip-network
    ssid:
      name: Netwerk
      icon: mdi:access-point-network
    mac_address:
      name: Mac-adres
      icon: mdi:folder-key-network-outline
      
  - platform: template
    name: "S0 Version"
    icon: "mdi:label-outline"
    update_interval: 6h
    lambda: return {"$p_version"};
      
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
