name: Build and Publish ESPHome firmware and website for Dongles

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: p1-dongle.yaml,p1-dongle-smr2_2.yaml,waterlezer.yaml
      # CHANGEME: Set the name of your project here:
      name: Dongles
